### PR TITLE
CMakeLists.txt not generating vcxproj correctly for static libraries #139

### PR DESCRIPTION
**Pull request by mattman71**
https://github.com/aws/aws-sdk-cpp/issues/139

This is the attempt I made to fix issue 139. It works for me, but somebody who knows what they are doing should probably review and/or fix it properly. I try to provide an idea for a solution when I point out an issue, so hopefully this helps enough. I'm a noob to aws-sdk-cpp, cmake, and github, so with that disclaimer, here it goes...

### CODE REVIEW

**Comment by JonathanHenson** [comment]
We've recently updated this in the CMakeLists file. Have a look and reopen if this doesn't solve your issue.

**Comment by mattman71** [comment]
Checking it out... will post back as soon as I validate. Thanks for the
notice!

On Mon, May 9, 2016 at 5:52 PM, Jonathan M. Henson <notifications@github.com

**Comment by bretambrose** [comment]
The new cmake params you'll want to use (you can drop the -DSTATIC_LINKING=1) are -DBUILD_SHARED_LIBS=OFF -DFORCE_SHARED_CRT=OFF.  Both of these default to ON to maintain existing behavior.

**Comment by mattman71** [comment]
I had only limited success with this. I can provide more console output or
logs as feedback if needed, but basically -DBUILD_SHARED_LIBS=OFF
-DFORCE_SHARED_CRT=OFF weren't enough. Still ended up with dynamic
libraries. I had to add -DMSVC=1 as well. However, this is where it gets
weird. Even that did not work, unless I ran the cmake (with those same
parameters) more than once. When running the cmake and it shows the CXX
flags and such that will be used, still came up with /MD, unless I ran with
all 3 of those -D parameters, and only if I ran the cmake 2 or more times
in a row, then I saw the proper /MTD type flags.

Should I open a new issue?

The good news is that at least I can use that work-around without having to
edit anything now, if I remember to do the hokie-pokie. :)

**Comment by bretambrose** [comment]
Reopen this please.  It looks like I either didn't test the fix (think I did) or I moved it around after testing it.  If you move the block from "# Compiler recognition" through "set_msvc_crt_settings()" down below "project(aws-sdk-cpp-all)", it should work properly.  As you discovered, MSVC wasn't set, so nothing was happening since the macro was getting run before the toolchain settings were finalized.

**Pull request closed without merging**
