### PR TITLE
added x-amz-request-id and x-amz-id-2 in GetObjectResult(S3) #554

### PR DESCRIPTION
**Pull request by amaneureka**

### CODE REVIEW

**Comment by singku** [comment]
These flies are generated by code generator based on service model. You will need to dive deep in dir code-generator.

**Comment by amaneureka** [comment]
Thanks @singku I have made the required changes. Could you please review it again ?

**Comment by amaneureka** [comment]
I have fixed merge conflicts can you please review the changes ?

@JonathanHenson

**Comment by singku** [comment]
@trevorrowe @amaneureka Source files under s3/model are auto generated based on api-description, you don't have to modify them. We have two ways to work this out: 
1: modify the api-description files, but this is auto-generated from our internal c2j service
2: adjust the code-generator for S3 [here](https://github.com/aws/aws-sdk-cpp/blob/master/code-generation/generator/src/main/java/com/amazonaws/util/awsclientgenerator/generators/cpp/s3/S3RestXmlCppClientGenerator.java)

**Comment by singku** [comment]
This request is going to be provided and merged shortly after code review.

**Pull request closed without merging**
