### PR TITLE
Dependency version bump

### PR DESCRIPTION
**Pull request by dougch**
*Issue #, if available:*
https://github.com/aws/aws-encryption-sdk-c/issues/450

*Description of changes:*
- bump aws-c-common to v0.4.13
- bump aws-checksums to v0.1.3
- bump aws-c-event-stream to v0.1.3
- README snippet about macOS

*Check all that applies:*
- [X] Did a review by yourself.
- [ ] Added proper tests to cover this PR. (If tests are not applicable, explain.)
- [ ] Checked if this PR is a breaking (APIs have been changed) change.
- [ ] Checked if this PR will _not_ introduce cross-platform inconsistent behavior.
- [X] Checked if this PR would require a ReadMe/Wiki update.

Check which platforms you have built SDK on to verify the correctness of this PR.
- [ ] Linux
- [ ] Windows
- [ ] Android
- [X] MacOS
- [ ] IOS
- [ ] Other Platforms

```
cmake -G Xcode -DTARGET_ARCH="APPLE" -DCMAKE_BUILD_TYPE=Debug ~/gitrepos/github.com/aws-sdk-cpp/
xcodebuild -target ALL_BUILD

...snip...

=== BUILD AGGREGATE TARGET ALL_BUILD OF PROJECT AWSSDK WITH THE DEFAULT CONFIGURATION (Debug) ===

Check dependencies

Write auxiliary files
write-file /var/tmp/build-cpp/AWSSDK.build/Debug/ALL_BUILD.build/Script-E413315A813640D7AD27CD47.sh
chmod 0755 /var/tmp/build-cpp/AWSSDK.build/Debug/ALL_BUILD.build/Script-E413315A813640D7AD27CD47.sh

PhaseScriptExecution CMake\ Rules /var/tmp/build-cpp/AWSSDK.build/Debug/ALL_BUILD.build/Script-E413315A813640D7AD27CD47.sh
    cd /Users/dougch/gitrepos/github.com/aws-sdk-cpp
    /bin/sh -c /var/tmp/build-cpp/AWSSDK.build/Debug/ALL_BUILD.build/Script-E413315A813640D7AD27CD47.sh
echo ""

echo Build\ all\ projects
Build all projects

** BUILD SUCCEEDED **

```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by singku** [comment]
We have an ongoing task that is going to bump the 3rd party versions

**Comment by singku** [comment]
But we will take the Readme update anyway.

**Comment by dougch** [comment]
> We have an ongoing task that is going to bump the 3rd party versions
Issue # or a link to more details?

**Comment by dougch** [comment]
> But we will take the Readme update anyway.

Split out these changes into [PR1268](https://github.com/aws/aws-sdk-cpp/pull/1268)

**Comment by singku** [comment]
merged

**Pull request closed without merging**
