### PR TITLE
adding AWS CodeBuild

### PR DESCRIPTION
**Pull request by chadbrewbaker**
AWSCodeBuild script for medium Ubuntu 14.04 image.

### CODE REVIEW

**Comment by JonathanHenson** [comment]
I don't see codebuild in here. Also, what are you using this script for?

**Comment by chadbrewbaker** [comment]
It is a CodeBuild script to compile the aws-sdk-cpp project.

Try it out, https://aws.amazon.com/codebuild/

You need to select a Ubuntu 14.04 build container, and choose at least a medium memory instance in the advanced options.

**Comment by JonathanHenson** [comment]
Ah! this is for building the SDK ON code build. Got it. I'll try and get this merged today. Thanks for the work!

**Comment by chadbrewbaker** [comment]
Any more work needed?

**Comment by JonathanHenson** [comment]
Thanks for this contribution! I've merged it internally, it's running through our CI now.

**Pull request merged**
