### PR TITLE
Updated aws-cpp-sdk-core's CMakeLists.txt

### PR DESCRIPTION
**Pull request by zeliard**
When I generate Visual Studio Solution (.sln) from cmake for SDK DLL, I'm in a spot of bother due to adding manually AWS_CUSTOM_MEMORY_MANAGEMENT into Visual Studio Project file.

So, how about adding AWS_CUSTOM_MEMORY_MANAGEMENT definition when USE_AWS_MEMORY_MANAGEMENT is ON?

### CODE REVIEW

**Comment by bretambrose** [comment]
Recent versions of the SDK should no longer need any definitions like this.  SDKConfig.h will get generated at configuration time and contain your memory management choice.

**Comment by zeliard** [comment]
AWS_CUSTOM_MEMORY_MANAGEMENT does not be defined in SDKConfig.h when doing cmake from the master branch of this repo.

**Comment by bretambrose** [comment]
What's in your SDKConfig.h?

**Comment by zeliard** [comment]
one line: 
#define USE_AWS_MEMORY_MANAGEMENT

but, I can't find the relation between USE_AWS_MEMORY_MANAGEMENT and AWS_CUSTOM_MEMORY_MANAGEMENT.

**Comment by bretambrose** [comment]
Oops, every reference to AWS_CUSTOM_MEMORY_MANAGEMENT should be replaced by USE_AWS_MEMORY_MANAGEMENT.  We'll push a fix soon.

**Comment by JonathanHenson** [comment]
this has been pushed. Thanks for your contriubtion.

**Pull request closed without merging**
