### PR TITLE
fix aws/aws-sdk-cpp#679

### PR DESCRIPTION
**Pull request by diablodale**
- included the Outcome header because the
  typedef SynthesizeSpeechOutcome needed it

### CODE REVIEW

**Comment by wps132230** [comment]
Hi, we have a forward declaration in `PollyClient.h`.
https://github.com/aws/aws-sdk-cpp/blob/75edd57e762606a2724a5dff564e8359c66adfee/aws-cpp-sdk-polly/include/aws/polly/PollyClient.h#L46
And you can include this header in your application cpp file, for example in `text-to-speech` tests:
https://github.com/aws/aws-sdk-cpp/blob/75edd57e762606a2724a5dff564e8359c66adfee/aws-cpp-sdk-text-to-speech-tests/TextToSpeechManagerTests.cpp#L20
Or do you have any other concerns?

**Comment by diablodale** [comment]
Those are workarounds for SDK errors. The SDK needs to be coherent and present an API that works clean and clear.

The fix that I provided solves this. It is the missing header file. Without that dependent header file, the API is nonfunctional. Please see the linked issue if you are unfamiliar with it.

It is not tenable for every one of your customers to digest your SDK, trace the bug, and apply the workaround. That is a tremendous waste of time and effort.

**Comment by marcomagdy** [comment]
You make a good point. Even though, technically the header is not needed to be `#include`ed in the client's header, it would make the out-of-the-box SDK experience easier. That being said, we should fix this across the SDK, and not just the Polly client.

Thanks for feedback.

**Comment by diablodale** [comment]
Closing PR, no action from Amazon.

**Pull request closed without merging**
