### PR TITLE
Fix error when using -DNO_HTTP_CLIENT=1

### PR DESCRIPTION
**Pull request by zwass**
Fixes issue #160

### CODE REVIEW

**Comment by zwass** [comment]
@JonathanHenson please take a look at this and merge when you can.

**Comment by bretambrose** [comment]
Rather than multiple #ifdefs, my preference would be to just add an AWS_UNREFERENCED_PARAM(clientConfiguration) to the #else clause.

**Comment by zwass** [comment]
Love it, updated, thanks @bretambrose.

**Comment by JonathanHenson** [comment]
Integrating now. Once we've confirmed the builds, we'll push it out.

**Comment by JonathanHenson** [comment]
This has been merged in.

**Pull request closed without merging**
