### PR TITLE
LibreSSL version 3.5.0 implements the OpenSSL 1.1.0 API

### PR DESCRIPTION
**Pull request by jorgen**
Compile with LibreSSL version 3.5.0

*Description of changes:*

LibreSSL version 3.5.0 and up implements the OpenSSL 1.1 API.

*Check all that applies:*
- [x ] Did a review by yourself.
- [ ] Added proper tests to cover this PR. (If tests are not applicable, explain.)
- [ ] Checked if this PR is a breaking (APIs have been changed) change.
- [ ] Checked if this PR will _not_ introduce cross-platform inconsistent behavior.
- [ ] Checked if this PR would require a ReadMe/Wiki update.

Check which platforms you have built SDK on to verify the correctness of this PR.
- [ x] Linux
- [ ] Windows
- [ ] Android
- [ ] MacOS
- [ ] IOS
- [x] Other Platforms

I have created a pullrequest for s2n:
https://github.com/aws/s2n-tls/pull/3589

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jorgen** [comment]
The patch for s2n has now been merged

**Comment by jorgen** [comment]
Do I need to do something more for this patch to be reviewed?

**Comment by SergeyRyabinin** [comment]
Hi @jorgen ,

Thank you a lot for your change. We definitely would prefer to merge this change.
We are performing more deep internal review and approval process, mostly because it touches the "security" code path. Personally, I don't see anything wrong as of now.
I hope it clarifies a bit the status of this PR, please sorry for a long review time.

Best regards,
Sergey

**Comment by jorgen** [comment]
@SergeyRyabinin I have updated the patch. This is a simple build fix for newer versions of LibreSSL. Surly forcing developers to use older versions of LibreSSL is a bigger security risk. The equivalent patch has been merged into s2n (https://github.com/aws/s2n-tls/pull/3589), so your library is using similar code from before.

**Review by sdavtaker — APPROVED** [review]

**Review by SergeyRyabinin — APPROVED** [review]

**Pull request merged**
