### PR TITLE
Add external project to readme

### LINKED ISSUE #1462: Add a sample External project for CPP SDK
**Is your feature request related to a problem? Please describe.**
This SDK can easily be used as an external project in projects.

**Describe the solution you'd like**
Add a sample ExternalProject_Add in the README.md

### PR DESCRIPTION
**Pull request by disa6302**
*Issue #, if available:*

#1462 
*Description of changes:*

*Check all that applies:*
- [X] Did a review by yourself.
- [] Added proper tests to cover this PR. (If tests are not applicable, explain.)
  Since it is a change in the README.md, tests are not required.
- [ ] Checked if this PR is a breaking (APIs have been changed) change.
- [X] Checked if this PR will _not_ introduce cross-platform inconsistent behavior.
- [X] Checked if this PR would require a ReadMe/Wiki update.

Check which platforms you have built SDK on to verify the correctness of this PR.
- [X] Linux
- [X] Windows
- [ ] Android
- [X] MacOS
- [ ] IOS
- [ ] Other Platforms

Resolved #1462 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by KaibaLopez** [comment]
Hi @disa6302 ,
Thanks for the PR. 
A couple notes:
We recently cleaned up the ReadMe to only include what we consider the basics to build the sdk and moved other info and guides to documents in the `Docs` folder. I think that it'd be better if we do the same for this. Or, we could have a guide written as a Wiki entry like we do for the ec2 app guide. What do you think though? If you have an argument for it being important or basic enough to be in the Readme we would reconsider putting it there.
If possible, could you also write it as a "from scratch" instructions guide or walkthrough, kind of the same way we have the dependency instructions?

If it is too much trouble I could also do those changes myself, just didn't want to take over, without asking first.

**Comment by disa6302** [comment]
@KaibaLopez , 

I do not mind having it added in docs and referencing it in the README.md. And sure, I can add a "from scratch" instructions guide. There would not be much to add, but I can definitely add some more steps around it sometime in the night.

**Comment by disa6302** [comment]
@KaibaLopez , 
I have made some changes per your suggestion. Let me know what you think.

**Comment by KaibaLopez** [comment]
Merged and thanks for the contribution!

**Pull request closed without merging**
