### PR TITLE
S3::URI

### PR DESCRIPTION
**Pull request by dvirtz**
*Issue #1507*

*Description of changes:*
- refactor Http::URI to a generic Net::URI.
- add S3::S3URI class.
- both Http::URI and S3::S3URI derive from Net::URI.

*Check all that applies:*
- [x] Did a review by yourself.
- [x] Added proper tests to cover this PR. (If tests are not applicable, explain.)
- [ ] Checked if this PR is a breaking (APIs have been changed) change.
- [ ] Checked if this PR will _not_ introduce cross-platform inconsistent behavior.
- [ ] Checked if this PR would require a ReadMe/Wiki update.

Check which platforms you have built SDK on to verify the correctness of this PR.
- [ ] Linux
- [ ] Windows
- [ ] Android
- [x] MacOS
- [ ] IOS
- [ ] Other Platforms

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dvirtz** [comment]
I'll be happy to get some hints about if and how to update documentation.

**Comment by KaibaLopez** [comment]
Hi @dvirtz ,
Can you provide some background on why this change is necessary? Like, what problem are you having that this fixes?

**Comment by dvirtz** [comment]
The background is shortly described in the attached issue, but to reiterate I'm getting an S3 URI from my library's clients and in order to call the S3 API I need to parse that URI into bucket, key etc. The added `S3URI` class solves that.

**Comment by jmklix** [comment]
Closing this because this is change is not backwards compatible

**Pull request closed without merging**
