### PR TITLE
[Transfer] Add a helper to get number of streamable bytes from start of a file

### PR DESCRIPTION
**Pull request by yundddd**
Currently the transfer manager provides convenient ways to run callbacks, such
as during status and progress updates. This gives a way for users to poll if
files are ready. One use case is to "stream" files to users, without waiting
for the entire file to finish downloading. It is possible for users to query
all completed parts and calculate how many bytes are ready for streaming, from
the start of the file.

This patch performs calculations when a part is completed successfully, and is
written to the underlying stream. It also adds an API for querying number of
bytes available from the beginning of the file, which removes locking and
accounting code from users who wish to use TransferManager asynchronously.

*Issue #, if available:*
#1636
*Description of changes:*
This patch performs calculations when a part is completed successfully, and is
written to the underlying stream. It also adds an API for querying number of
bytes available from the beginning of the file, which removes locking and
accounting code from users who wish to use TransferManager asynchronously.

*Check all that applies:*
- [x] Did a review by yourself.
- [x] Added proper tests to cover this PR. (If tests are not applicable, explain.)
- [x] Checked if this PR is a breaking (APIs have been changed) change.
- [x] Checked if this PR will _not_ introduce cross-platform inconsistent behavior.
- [x] Checked if this PR would require a ReadMe/Wiki update.

Check which platforms you have built SDK on to verify the correctness of this PR.
- [x] Linux
- [ ] Windows
- [ ] Android
- [ ] MacOS
- [ ] IOS
- [ ] Other Platforms

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by timtianyang** [comment]
Anyone available for reviews? @KaibaLopez

**Comment by KaibaLopez** [comment]
Yes, sorry for the lack of response, 
The PR does make sense and I'm trying to have it merged, just need to write up a test for it, to make sure it is returning the correct values.

Again, sorry for the delay here.

**Comment by timtianyang** [comment]
Hey @KaibaLopez  I tried adding a test but the reporting of streamable bytes is very racy in nature, and hard to really deterministically test for. Can you take a look at the test I added? It only checks a successful download not an in-progress one.

It doesn't look like there is a CI for this repo. My setup can't run these integration tests but I have tested and made sure the streamable bytes feature works in my application from work.

**Comment by KaibaLopez** [comment]
Quick update, tried running our CI tests and I'm seeing some errors.
 I am working on fixing those and adding a test for "in progress"  checks.

**Comment by timtianyang** [comment]
@KaibaLopez Do you have any luck? Any chance we can get this into the up-coming release?

**Comment by KaibaLopez** [comment]
@timtianyang , Sorry yea, kind of stretched on bandwith here, but trying to get it in by the end of the week.

**Review by Terrybrar97 — APPROVED** [review]
T WEOURUS

**Comment by timtianyang** [comment]
@KaibaLopez I swear I saw a PR approval notification from Terrybrar97 but it's not showing up on here, nor is that person on the maintainer list. 😕

**Comment by KaibaLopez** [comment]
Real sorry it took this long, the release has been pushed to prioritize other fixes and internal stuff, but the PR is accepted and it will be in the next release.
Thanks for the PR and again, real sorry it took this long, I'll try to push harder for merging PRs in the future.

**Pull request closed without merging**
