### PR TITLE
[aws-cpp-sdk-core]: fix race condition in cJSON_AS4CPP_Parse.* calls

### LINKED ISSUE #2230: [aws-cpp-sdk-core]: race condition in cJSON_AS4CPP_Parse.* calls
### Describe the bug

_This is the same problem as reported in https://github.com/awslabs/aws-c-common/issues/953, it happens on 1.10.18 and later._

### Problem description

The included `cJSON.c` uses a `static` `global_error` variable, which is not read from (`cJSON_AS4CPP_GetErrorPtr` is not used by the code, as it is not thread-safe).

However, concurrent calls to `cJSON_AS4CPP_Parse.*` routines mutually overwrite the global variable.
This triggers a _race condition error_ when using the thread sanitizer.

### Error trace

```console
WARNING: ThreadSanitizer: data race (pid=19018)
  Write of size 8 at 0x7f9dd2c40238 by thread T29:
    #0 cJSON_AS4CPP_ParseWithLengthOpts external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/external/cjson/cJSON.cpp:1111 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-core.so+0x3466a5)
    #1 cJSON_AS4CPP_ParseWithOpts external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/external/cjson/cJSON.cpp:1101 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-core.so+0x3465c3)
    #2 JsonValue external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/utils/json/JsonSerializer.cpp:31 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-core.so+0x43a264)
    #3 Aws::Internal::Endpoint::EndpointAttributes::BuildEndpointAttributesFromJson(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/endpoint/internal/AWSEndpointAttribute.cpp:35 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-core.so+0x34340d)
    #4 Aws::Endpoint::ResolveEndpointDefaultImpl(Aws::Crt::Endpoints::RuleEngine const&, std::vector<Aws::Endpoint::EndpointParameter, std::allocator<Aws::Endpoint::EndpointParameter> > const&, std::vector<Aws::Endpoint::EndpointParameter, std::allocator<Aws::Endpoint::EndpointParameter> > const&, std::vector<Aws::Endpoint::EndpointParameter, std::allocator<Aws::Endpoint::EndpointParameter> > const&) external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/endpoint/DefaultEndpointProvider.cpp:178 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-core.so+0x338cb5)
    #5 Aws::Endpoint::DefaultEndpointProvider<Aws::S3Crt::S3CrtClientConfiguration, Aws::S3Crt::Endpoint::S3CrtBuiltInParameters, Aws::S3Crt::Endpoint::S3CrtClientContextParameters>::ResolveEndpoint(std::vector<Aws::Endpoint::EndpointParameter, std::allocator<Aws::Endpoint::EndpointParameter> > const&) const external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/endpoint/DefaultEndpointProvider.h:76 (s3_blobstore_plugin_test+0x511832)
    #6 Aws::S3Crt::S3CrtClient::ListObjectsV2(Aws::S3Crt::Model::ListObjectsV2Request const&) const external/com_github_aws-sdk-cpp/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp:2703 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-s3-crt.so+0x3c6448)
...
  Previous write of size 8 at 0x7f9dd2c40238 by thread T28:
    #0 cJSON_AS4CPP_ParseWithLengthOpts external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/external/cjson/cJSON.cpp:1111 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-core.so+0x3466a5)
    #1 cJSON_AS4CPP_ParseWithOpts external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/external/cjson/cJSON.cpp:1101 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-core.so+0x3465c3)
    #2 JsonValue external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/utils/json/JsonSerializer.cpp:31 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-core.so+0x43a264)
    #3 Aws::Internal::Endpoint::EndpointAttributes::BuildEndpointAttributesFromJson(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/endpoint/internal/AWSEndpointAttribute.cpp:35 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-core.so+0x34340d)
    #4 Aws::Endpoint::ResolveEndpointDefaultImpl(Aws::Crt::Endpoints::RuleEngine const&, std::vector<Aws::Endpoint::EndpointParameter, std::allocator<Aws::Endpoint::EndpointParameter> > const&, std::vector<Aws::Endpoint::EndpointParameter, std::allocator<Aws::Endpoint::EndpointParameter> > const&, std::vector<Aws::Endpoint::EndpointParameter, std::allocator<Aws::Endpoint::EndpointParameter> > const&) external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/endpoint/DefaultEndpointProvider.cpp:178 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-core.so+0x338cb5)
    #5 Aws::Endpoint::DefaultEndpointProvider<Aws::S3Crt::S3CrtClientConfiguration, Aws::S3Crt::Endpoint::S3CrtBuiltInParameters, Aws::S3Crt::Endpoint::S3CrtClientContextParameters>::ResolveEndpoint(std::vector<Aws::Endpoint::EndpointParameter, std::allocator<Aws::Endpoint::EndpointParameter> > const&) const external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/endpoint/DefaultEndpointProvider.h:76 (s3_blobstore_plugin_test+0x511832)
    #6 Aws::S3Crt::S3CrtClient::ListObjectsV2(Aws::S3Crt::Model::ListObjectsV2Request const&) const external/com_github_aws-sdk-cpp/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp:2703 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-s3-crt.so+0x3c6448)
...
  Thread T29 (tid=19062, running) created by main thread at:
    #0 pthread_create /local/mnt/workspace/bcain_clang_bcain-ubuntu_7561/final/llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:966 (s3_blobstore_plugin_test+0x47ee0b)
    #1 std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) ??:? (libstdc++.so.6+0xbd994)
    #2 Aws::Utils::Threading::DefaultExecutor::SubmitToThread(std::function<void ()>&&) external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/utils/threading/Executor.cpp:28 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-core.so+0x455652)
    #3 bool Aws::Utils::Threading::Executor::Submit<Aws::S3Crt::S3CrtClient::ListObjectsV2Async(Aws::S3Crt::Model::ListObjectsV2Request const&, std::function<void (Aws::S3Crt::S3CrtClient const*, Aws::S3Crt::Model::ListObjectsV2Request const&, Aws::Utils::Outcome<Aws::S3Crt::Model::ListObjectsV2Result, Aws::S3Crt::S3CrtError> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const::$_185>(Aws::S3Crt::S3CrtClient::ListObjectsV2Async(Aws::S3Crt::Model::ListObjectsV2Request const&, std::function<void (Aws::S3Crt::S3CrtClient const*, Aws::S3Crt::Model::ListObjectsV2Request const&, Aws::Utils::Outcome<Aws::S3Crt::Model::ListObjectsV2Result, Aws::S3Crt::S3CrtError> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const::$_185&&) external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/threading/Executor.h:42 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-s3-crt.so+0x3c73d9)
    #4 Aws::S3Crt::S3CrtClient::ListObjectsV2Async(Aws::S3Crt::Model::ListObjectsV2Request const&, std::function<void (Aws::S3Crt::S3CrtClient const*, Aws::S3Crt::Model::ListObjectsV2Request const&, Aws::Utils::Outcome<Aws::S3Crt::Model::ListObjectsV2Result, Aws::S3Crt::S3CrtError> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const external/com_github_aws-sdk-cpp/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp:2721 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-s3-crt.so+0x3c7271)
...
  Thread T28 (tid=19061, running) created by main thread at:
    #0 pthread_create /local/mnt/workspace/bcain_clang_bcain-ubuntu_7561/final/llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:966 (s3_blobstore_plugin_test+0x47ee0b)
    #1 std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) ??:? (libstdc++.so.6+0xbd994)
    #2 Aws::Utils::Threading::DefaultExecutor::SubmitToThread(std::function<void ()>&&) external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/utils/threading/Executor.cpp:28 (libexternal_Scom_Ugithub_Uaws-sdk-
cpp_Slibaws-core.so+0x455652)
    #3 bool Aws::Utils::Threading::Executor::Submit<Aws::S3Crt::S3CrtClient::ListObjectsV2Async(Aws::S3Crt::Model::ListObjectsV2Request const&, std::function<void (Aws::S3Crt::S3CrtClient const*, Aws::S3Crt::Mod
el::ListObjectsV2Request const&, Aws::Utils::Outcome<Aws::S3Crt::Model::ListObjectsV2Result, Aws::S3Crt::S3CrtError> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_pt
r<Aws::Client::AsyncCallerContext const> const&) const::$_185>(Aws::S3Crt::S3CrtClient::ListObjectsV2Async(Aws::S3Crt::Model::ListObjectsV2Request const&, std::function<void (Aws::S3Crt::S3CrtClient const*, Aws:
:S3Crt::Model::ListObjectsV2Request const&, Aws::Utils::Outcome<Aws::S3Crt::Model::ListObjectsV2Result, Aws::S3Crt::S3CrtError> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const::$_185&&) external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/threading/Executor.h:42 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-s3-crt.so+0x3c73d9)
    #4 Aws::S3Crt::S3CrtClient::ListObjectsV2Async(Aws::S3Crt::Model::ListObjectsV2Request const&, std::function<void (Aws::S3Crt::S3CrtClient const*, Aws::S3Crt::Model::ListObjectsV2Request const&, Aws::Utils::Outcome<Aws::S3Crt::Model::ListObjectsV2Result, Aws::S3Crt::S3CrtError> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const external/com_github_aws-sdk-cpp/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp:2721 (libexternal_Scom_Ugithub_Uaws-sdk-cpp_Slibaws-s3-crt.so+0x3c7271)
    #5 av::cloud::aws::s3::S3BlobstorePlugin::list_info(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) cloud/aws/s3/s3_blobstore_plugin.cc:185 (libcloud_Saws_Ss3_Slibs3_Ublobstore_Uplugin_Ucpp.so+0x518f5)
```

### What to do 

As in https://github.com/awslabs/aws-c-common/pull/954, in order to not slow down operations by protecting writes to the unused global variable with a `mutex`, the best solution seems to be to not write to it in the first place.

### AWS CPP SDK version used

1.10.18 (problem also present on `master`).

### Compiler and Version used

gcc / clang

### Operating System and version

Linux, ubuntu 18.04

### PR DESCRIPTION
**Pull request by grrtrr**
When calling `cJSON_AS4CPP_Parse.*` routines, there is a race condition in mutually overwriting the `static` `global_error` variable. This race condition will be flagged by the thread sanitizer.

As in https://github.com/awslabs/aws-c-common/pull/954, avoid the race condition on the (otherwise unused) global variable by not writing to it in the first place.

Resolves #2230.

*Check all that applies:*
- [X] Did a review by yourself.
- [X] Added proper tests to cover this PR. (If tests are not applicable, explain.)
- [X] Checked if this PR is a breaking (APIs have been changed) change.
- [X] Checked if this PR will _not_ introduce cross-platform inconsistent behavior.
- [X] Checked if this PR would require a ReadMe/Wiki update.

Check which platforms you have built SDK on to verify the correctness of this PR.
- [X] Linux
- [ ] Windows
- [ ] Android
- [ ] MacOS
- [ ] IOS
- [ ] Other Platforms

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by SergeyRyabinin — APPROVED** [review]

**Comment by SergeyRyabinin** [comment]
Hi @grrtrr ,
thanks a lot for spotting and reporting this issue.
We will merge this PR shortly (if it passes the CI), otherwise we will fix where it fails and merge anyway.

Best regards,
Sergey

**Comment by grrtrr** [comment]
> Best regards, Sergey

Thank you.

**Comment by SergeyRyabinin** [comment]
Hi @grrtrr ,

I've tried your PR and unfortunately, it is not very compatible with cJSON.
cJSON lib uses this block to report parsing error:
```
    if (value != NULL)
    {
        error local_error;
        local_error.json = (const unsigned char*)value;
        local_error.position = 0;

        if (buffer.offset < buffer.length)
        {
            local_error.position = buffer.offset;
        }
        else if (buffer.length > 0)
        {
            local_error.position = buffer.length - 1;
        }

        if (return_parse_end != NULL)
        {
            *return_parse_end = (const char*)local_error.json + local_error.position;
        }

        global_error = local_error;
    }
```
i.e. it cannot be removed as of now.
I made a change that removes only global object and it's corresponding API: https://github.com/aws/aws-sdk-cpp/commit/1a7773c4d7027893f9c9d8c9971369ca21d384fb

I'm going to discuss with the team the way forward and get back to you shortly.

Best regards,
Sergey

**Comment by grrtrr** [comment]
> i.e. it cannot be removed as of now. 

You are correct, I removed too much code. The `cJSON_AS4CPP_GetErrorPtr()` function is [not thread-safe](https://cjson.docsforge.com/#:~:text=at%20compile%20time.-,Thread%20Safety,cJSON%20is%20not%20thread%20safe), neither are the functions that write to `global_error`.

The main SDK code does not use `cJSON_AS4CPP_GetErrorPtr()` anywhere.

Hence I will update this PR and https://github.com/awslabs/aws-c-common/pull/954 to disable `cJSON_AS4CPP_GetErrorPtr()` and `global_error`, as in your PR. Commenting out may be better, to document the fact that the affected code is not safe for multi-threaded applications.

**Comment by grrtrr** [comment]
@SergeyRyabinin - I have updated this PR and https://github.com/awslabs/aws-c-common/pull/954 (same change) with regard to your comments. Could you take another look, please?

**Comment by SergeyRyabinin** [comment]
Hi @grrtrr,
Thanks a lot for the update.
```
CJSON_AS4CPP_PUBLIC(const char *) cJSON_AS4CPP_GetErrorPtr(void);
```
Could you please also comment out a function in the header?

**Review by SergeyRyabinin — APPROVED** [review]

**Review by jmklix — APPROVED** [review]

**Pull request merged**
